id: I2F4ACBEB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:57:18+00:00'
last_modified: '2022-06-08T08:50:41.580510+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25095
  title: བོད་ཀྱི་བོན་དགོན་ཁག་གི་ལོ་རྒྱུས་དང་ད་ལྟའི་གནས་བབ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EEDD:
      image_group_id: I5782
      title: ''
      total_pages: 358
      order: 1
      base_file: EEDD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
