id: P009131
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:24:31.737071
source_metadata:
  id: bdr:W25095
  title: བོད་ཀྱི་བོན་དགོན་ཁག་གི་ལོ་རྒྱུས་དང་ད་ལྟའི་གནས་བབ
  author: ''
  volumes:
    87a8827815d04b7990d390d57a757490:
      image_group_id: I5782
      title: ''
      volume_number: 1
      total_pages: 358
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
